added initial files
nimdolphin/js-tasks pull request #1
Opened 2022-08-31 22:52 UTC by nimdolphin

2022-09-03 06:22 UTC, kathrynowy requested changes

2022-09-03 06:22 UTC, kathrynowy commented on index.js
> +if (javaScript == "ECMAScript") {
strcit comparison

2022-09-03 06:22 UTC, kathrynowy commented on index.js
> +  login == "Сотрудник"
strict comparison

2022-09-03 06:22 UTC, kathrynowy commented on index.js
> +if (b == 10) {
same, check everywhere

2022-09-03 06:22 UTC, kathrynowy commented on index.js
> +if (c == 0) {
we don't check like this

2022-09-03 14:13 UTC, nimdolphin commented on index.js
> +if (javaScript == "ECMAScript") {
fixed

2022-09-03 14:13 UTC, nimdolphin commented on index.js
> +  login == "Сотрудник"
fixed

2022-09-03 14:13 UTC, nimdolphin commented on index.js
> +if (b == 10) {
fixed

2022-09-03 14:13 UTC, nimdolphin commented on index.js
> +if (c == 0) {
fixed

2022-09-08 19:34 UTC, kathrynowy approved these changes

2022-09-16 07:26 UTC, merged