I made tasks with cycles
nimdolphin/js-tasks pull request #3
Opened 2022-09-08 14:32 UTC by nimdolphin

2022-09-08 19:33 UTC, kathrynowy requested changes

2022-09-08 19:33 UTC, kathrynowy commented on index.js
> +document.write("1<br>");
что это?

2022-09-16 11:02 UTC, nimdolphin commented on index.js
> +document.write("1<br>");
fixed

2022-09-17 20:17 UTC, kathrynowy requested changes

2022-09-17 20:17 UTC, kathrynowy commented on cycles.js
> +//     if (m % q === 0) continue numb;
```suggestion
//     if (!m % q) continue numb;
```

2022-09-17 20:25 UTC, merged