made switch tasks
nimdolphin/js-tasks pull request #4
Opened 2022-09-08 14:55 UTC by nimdolphin

2022-09-08 19:30 UTC, kathrynowy requested changes

2022-09-08 19:30 UTC, kathrynowy commented on index.js
> +abc = symbolA;
why do you need here 2 variables?

2022-09-08 19:30 UTC, kathrynowy commented on index.js
> +}
do it in 1 line with ternary operator pls (and 1 console.log only)

2022-09-08 19:30 UTC, kathrynowy commented on index.js
> +str = str2;
same here

2022-09-16 07:42 UTC, nimdolphin commented on index.js
> +abc = symbolA;
fixed

2022-09-16 07:43 UTC, nimdolphin commented on index.js
> +str = str2;
fixed

2022-09-16 10:23 UTC, nimdolphin commented on index.js
> +}
fixed

2022-09-17 20:18 UTC, kathrynowy approved these changes

2022-09-17 20:24 UTC, merged