made tasks for functions
nimdolphin/js-tasks pull request #5
Opened 2022-09-20 11:17 UTC by nimdolphin

2022-10-05 19:53 UTC, kathrynowy requested changes

2022-10-05 19:53 UTC, kathrynowy commented on function-tasks.css
> +  border: 1 px, solid, red;
мы так не пишем

2022-10-05 19:53 UTC, kathrynowy commented on function-tasks.js
> +    console.log(undefined);
? что за лог андефайнд?

2022-10-05 19:53 UTC, kathrynowy commented on function-tasks.js
> +    return 0;
тебе не нужен последний else if
потому что если одно число не больше и не меньше другого - они равны

2022-10-05 19:53 UTC, kathrynowy commented on function-tasks.js
> +  return a > b ? 1 : a < b ? -1 : a === b ? 0 : undefined;
убрать undefined
последняя проверка на ноль не нужна

2022-10-05 19:53 UTC, kathrynowy commented on function-tasks.js
> +  } else if (i % 2 === 1 && j % 2 === 1) {
мы не проверяем так
процент от деления может быть либо 1 либо 0 - либо true либо flase

2022-10-05 19:53 UTC, kathrynowy commented on function-tasks.js
> +  } else if (i % 2 === 1 && j % 2 === 1) {
вынести проверку в переменнуб
чтобы не выполнять одно и то же 20 раз

2022-10-05 19:53 UTC, kathrynowy commented on function-tasks.js
> +  } else if (!a) {
тебе не нужен этот else if

2022-10-05 19:53 UTC, kathrynowy commented on function-tasks.js
> +  } else if (!a) {
обьясни мне в лс теперь почему

2022-10-06 21:00 UTC, nimdolphin commented on function-tasks.css
> +  border: 1 px, solid, red;
fixed

2022-10-06 21:00 UTC, nimdolphin commented on function-tasks.js
> +    console.log(undefined);
fixed

2022-10-06 21:00 UTC, nimdolphin commented on function-tasks.js
> +    return 0;
fixed

2022-10-06 21:00 UTC, nimdolphin commented on function-tasks.js
> +  return a > b ? 1 : a < b ? -1 : a === b ? 0 : undefined;
fixed

2022-10-06 21:00 UTC, nimdolphin commented on function-tasks.js
> +  } else if (i % 2 === 1 && j % 2 === 1) {
fixed

2022-10-06 21:00 UTC, nimdolphin commented on function-tasks.js
> +  } else if (i % 2 === 1 && j % 2 === 1) {
fixed

2022-10-06 21:01 UTC, nimdolphin commented on function-tasks.js
> +  } else if (!a) {
fixed

2022-10-10 20:48 UTC, kathrynowy approved these changes

2022-10-10 20:52 UTC, merged