added string tasks
nimdolphin/js-tasks pull request #7
Opened 2022-11-05 13:57 UTC by nimdolphin

2022-11-09 17:07 UTC, kathrynowy requested changes

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +  }
?

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +}
write in 1 line with an arrow func and implicit return

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +  }
same here

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +  return +str.slice(1);
what if str will come 'dfdf'

try it out

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +const newStr1 = str1.replace(/[$]/gi, "*");
what does it mean gi?

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +const newStr1 = str1.replace(/[$]/gi, "*");
don't we have replaceAll?

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +};
why do u use explicit return?

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +  if (str3 === String || length > 0) {
??

1 how can "hey hubby" be an object like String?

<img width="283" alt="image" src="https://user-images.githubusercontent.com/43656351/200893770-0135706a-394b-43b8-af80-9ccbcadc8bd0.png">


2 we don;t check >0 like this if there is only range (0 - ..... any amount)

you can check for zero !length
and for other values - just  (length)


I described it in TG many times, please follow it

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +}
arrow func

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +  return newStr;
do u need a new variable/clg?

please make your code clean

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +  console.log(newArr);
your function is returning nothing

it's useless then

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +  console.log(str[0].toUpperCase() + str.slice(1));
same

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +      newS += smallW;
can u do it in 1 line?

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +      newS += smallW;
and do u really need bigW variable?

and what does it mean W??

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +      console.log(str5[i].toLowerCase());
?? remove your logs when you push the code into repository

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +      strNew5 += str5[i].toUpperCase();
same in 1 line

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +  }
can you just return make 1 result?


create a string with zeros
and add sign there

then convert to number.

2022-11-09 17:07 UTC, kathrynowy commented on string-tasks.js
> +  }
can you do it in 1 line?
just slice a needed amount

2022-11-30 09:42 UTC, nimdolphin commented on string-tasks.js
> +  }
fixed

2022-11-30 09:46 UTC, nimdolphin commented on string-tasks.js
> +}
fixed

2022-11-30 09:50 UTC, nimdolphin commented on string-tasks.js
> +  }
fixed

2022-11-30 09:53 UTC, nimdolphin commented on string-tasks.js
> +  return +str.slice(1);
fixed

2022-11-30 09:54 UTC, nimdolphin commented on string-tasks.js
> +const newStr1 = str1.replace(/[$]/gi, "*");
fixed

2022-11-30 09:56 UTC, nimdolphin commented on string-tasks.js
> +};
fixed

2022-11-30 09:58 UTC, nimdolphin commented on string-tasks.js
> +  if (str3 === String || length > 0) {
fixed

2022-11-30 10:00 UTC, nimdolphin commented on string-tasks.js
> +}
fixed

2022-11-30 10:01 UTC, nimdolphin commented on string-tasks.js
> +  return newStr;
fixed

2022-11-30 10:02 UTC, nimdolphin commented on string-tasks.js
> +  console.log(newArr);
fixed

2022-11-30 10:03 UTC, nimdolphin commented on string-tasks.js
> +  console.log(str[0].toUpperCase() + str.slice(1));
fixed

2022-11-30 10:09 UTC, nimdolphin commented on string-tasks.js
> +      newS += smallW;
fixed

2022-11-30 10:10 UTC, nimdolphin commented on string-tasks.js
> +      console.log(str5[i].toLowerCase());
fixed

2022-11-30 10:11 UTC, nimdolphin commented on string-tasks.js
> +      strNew5 += str5[i].toUpperCase();
fixed

2022-11-30 10:12 UTC, nimdolphin commented on string-tasks.js
> +  }
fixed

2022-11-30 10:15 UTC, nimdolphin commented on string-tasks.js
> +  }
fixed

2022-12-02 19:35 UTC, kathrynowy requested changes

2022-12-02 19:35 UTC, kathrynowy commented on string-tasks.js
> +    : newStr.slice(0, idx).join(" ");
?

2022-12-02 19:35 UTC, kathrynowy commented on string-tasks.js
> +    strNew5 += strN;
```suggestion
    let strN = !(i % 2) ? str5[i].toLowerCase() : str5[i].toUpperCase();
    
    strNew5 += strN;
```

2022-12-02 19:35 UTC, kathrynowy commented on string-tasks.js
> +  return strNew5;
```suggestion
  }
  
  return strNew5;
```

2022-12-02 19:35 UTC, kathrynowy commented on string-tasks.js
> +
```suggestion

    let newS2 = smallLetter;
    
    if (newS === smallLetter){
    newS2 = bigLetter ;
    }

```

2022-12-02 19:35 UTC, kathrynowy commented on string-tasks.js
> +  return newStr;
1 line all func

2022-12-12 11:47 UTC, nimdolphin commented on string-tasks.js
> +    : newStr.slice(0, idx).join(" ");
fixed

2022-12-12 11:49 UTC, nimdolphin commented on string-tasks.js
> +    strNew5 += strN;
fixed

2022-12-12 11:50 UTC, nimdolphin commented on string-tasks.js
> +  return strNew5;
fixed

2022-12-12 12:24 UTC, nimdolphin commented on string-tasks.js
> +
fixed

2022-12-12 12:29 UTC, nimdolphin commented on string-tasks.js
> +  return newStr;
fixed

2023-01-02 18:23 UTC, kathrynowy approved these changes

2023-01-02 18:23 UTC, kathrynowy commented on string-tasks.js
> +const removeSymbols = (str3, length) =>
Точно ли такое словио должно быть? Если нет строки или нет длины - ты обрезаешь
иначе нет

должно быть наоборот?

2023-01-02 18:23 UTC, kathrynowy commented on string-tasks.js
> +function repeatStr(str, n) {
In1 line

2023-01-13 23:19 UTC, nimdolphin commented on string-tasks.js
> +const removeSymbols = (str3, length) =>
fixed

2023-01-13 23:19 UTC, nimdolphin commented on string-tasks.js
> +function repeatStr(str, n) {
fixed

2023-01-13 23:20 UTC, merged