made array tasks
nimdolphin/js-tasks pull request #8
Opened 2022-11-30 15:45 UTC by nimdolphin

2022-12-02 19:21 UTC, kathrynowy requested changes

2022-12-02 19:21 UTC, kathrynowy commented on array.html
> +
?

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +  return newArr;
in 1 line arrow func

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +  if (i % 2 === 1) continue;
```suggestion
  if (i % 2) continue;
```

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +const newStr2 = newStr.join(", ");
in 1 line pls

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +    }
?

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +  return sortNum.at(-1);
?

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +  const findMin = arr15.sort((a, b) => a - b);
цкшеу фwrite your own implementation without sort

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +  for (i = 0; i < arr16.length; i++) {
use reduce

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +  for (i = 0; i < arr16.length; i++) {
without google!!

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +  return new Array(arraySize).fill(value);
do not use fill

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +  return newArr;
1 line

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +  return obj;
you are gonna explain this for me at the call
you will write this again

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +    return {
why do u write an explicit return??

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +  return numbers;
why do u need destructuring here??

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +  return array.filter((item, id) => array.indexOf(item) === id);
what else can we use?

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +}
зачем тебе лишняя переменная

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +  }
1 return

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +//       let num = arr[j];
ты создаешь эту переменную над условием, даже если не меняешь местами переменные
занимаеш память юзера

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +//       let num = arr[j];
+ меняем переменные местами в 1 строчку

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +}
что за одинаковые функции? зачем??
функция принимает массив как параметр и его сортирует
тебе нужно понять зачем нам вообще функции

копипаст кода

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +    console.log(middleNum);
?

2022-12-02 19:21 UTC, kathrynowy commented on array.js
> +    }
remove last else
it will be excecuted any way

2023-01-02 18:31 UTC, kathrynowy requested changes

2023-01-02 18:31 UTC, kathrynowy commented on array.js
> +const sortNum1 = () => arr1.sort((a, b) => b - a);
Зачем здесь внутри функция?

2023-01-02 18:31 UTC, kathrynowy commented on array.js
> +  arr.reduce((value, sum) => value + sum, 0) / arr.length;
Что значит здесь 0? В лс ответь

2023-01-02 18:31 UTC, kathrynowy commented on array.js
> +  array.reduce((accum, item) => {
А что значит пустой объект?

2023-01-02 18:31 UTC, kathrynowy commented on array.js
> +const isEqual = (firstArray, secondArray) => {
Функция очень нечитебальная

сделай условия выхода

не в одном ретурн все


If (!arr.length || !arrr2.length || arr.length!== arr2.length) {
Return false’;
} etc.

2023-01-02 18:31 UTC, kathrynowy commented on array.js
> +    return newArr;
Почему в while return?

2023-01-02 18:31 UTC, kathrynowy commented on array.js
> +const isPositive = (arr1) => arr1.filter((item) => item > -1);
> 0

2023-01-02 18:31 UTC, kathrynowy commented on array.js
> +  i++;
Неверно создавать переменную вне функции

2023-01-02 18:31 UTC, kathrynowy commented on array.js
> +function BinarSort(sortArr, key) {
Binary search

2023-01-02 18:31 UTC, kathrynowy commented on array.js
> +    } else if (middleNum < key) {
Why else if ?

just if

you have return above

2023-01-11 18:10 UTC, kathrynowy commented on array.html
> +
dffd

2023-01-11 18:11 UTC, nimdolphin commented on array.html
> +
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +  return newArr;
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +  if (i % 2 === 1) continue;
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +const newStr2 = newStr.join(", ");
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +    }
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +  return sortNum.at(-1);
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +  const findMin = arr15.sort((a, b) => a - b);
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +  for (i = 0; i < arr16.length; i++) {
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +  return new Array(arraySize).fill(value);
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +  return newArr;
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +  return obj;
ok

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +    return {
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +  return numbers;
чтоб собрать все параметры.

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +  return array.filter((item, id) => array.indexOf(item) === id);
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +}
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +  }
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +//       let num = arr[j];
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +}
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +    console.log(middleNum);
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +    }
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +const sortNum1 = () => arr1.sort((a, b) => b - a);
fixed

2023-01-11 18:11 UTC, nimdolphin commented on array.js
> +  arr.reduce((value, sum) => value + sum, 0) / arr.length;
fixed

2023-01-11 18:19 UTC, nimdolphin commented on array.js
> +  array.reduce((accum, item) => {
fixed

2023-01-11 18:20 UTC, nimdolphin commented on array.js
> +const isEqual = (firstArray, secondArray) => {
fixed

2023-01-11 18:20 UTC, nimdolphin commented on array.js
> +    return newArr;
fixed

2023-01-11 18:20 UTC, nimdolphin commented on array.js
> +const isPositive = (arr1) => arr1.filter((item) => item > -1);
fixed

2023-01-11 18:20 UTC, nimdolphin commented on array.js
> +  i++;
fixed

2023-01-11 18:20 UTC, nimdolphin commented on array.js
> +function BinarSort(sortArr, key) {
fixed

2023-01-11 18:20 UTC, nimdolphin commented on array.js
> +    } else if (middleNum < key) {
fixed

2023-02-20 20:42 UTC, kathrynowy requested changes

2023-02-20 20:42 UTC, kathrynowy commented on array.js
> +    if (arr12[i] === arr12[i - 1]) {
Ternary

2023-02-20 20:42 UTC, kathrynowy commented on array.js
> +  const uniq = new Set(array);
```suggestion
  Return […new Set(array)]
```

2023-04-12 23:05 UTC, nimdolphin commented on array.js
> +    if (arr12[i] === arr12[i - 1]) {
fixed

2023-04-12 23:11 UTC, nimdolphin commented on array.js
> +  const uniq = new Set(array);
fixed

2023-04-12 23:20 UTC, closed without merging